package com.singraul.ecommerce.dao;

import com.singraul.ecommerce.entity.Product;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestParam;

@CrossOrigin("http://localhost:4200") // allow access from angular app  at port 4200
public interface ProductRepository extends JpaRepository<Product,Long> {
    // http://localhost:8080/api/products/search/findByCategoryId?id=1
    // above url is automatically generated by spring data rest
    // behind the scene below query will be executed on the database
    // select * from product where category_id=?
    Page<Product> findByCategoryId(@RequestParam("id") Long id, Pageable pageable);
    // Behind the scene below query will be executed on the database
    // select * from Product P where p.name LIKE concat('%',:name,'%')
    Page<Product> findByNameContaining(@RequestParam("name")String name ,Pageable pageable);
}
